<?php

// if( function_exists('acf_add_local_field_group') ):

// acf_add_local_field_group(array(
// 	'key' => 'group_5df69a5b2ad62',
// 	'title' => 'Slider',
// 	'fields' => array(
// 		array(
// 			'key' => 'field_main_slider_image_bg',
// 			'label' => 'Main Image Background',
// 			'name' => 'main_image_bg',
// 			'type' => 'image',
// 			'instructions' => 'a background image for the slider image',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'return_format' => 'url',
// 			'preview_size' => 'medium',
// 			'library' => 'all',
// 		),
// 		array(
// 			'key' => 'field_5df69de723ecc',
// 			'label' => 'Content',
// 			'name' => 'content',
// 			'type' => 'repeater',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'collapsed' => '',
// 			'min' => 0,
// 			'max' => 0,
// 			'layout' => 'block',
// 			'button_label' => 'Add Content',
// 			'sub_fields' => array(
// 				array(
// 					'key' => 'field_5df6a0b023ed1',
// 					'label' => 'Title',
// 					'name' => 'title',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => 'field_5df6a64f23ed3',
// 					'label' => 'Description',
// 					'name' => 'description',
// 					'type' => 'wysiwyg',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'maxlength' => '',
// 					'rows' => '',
// 					'new_lines' => '',
// 				),
// 				array(
// 					'key' => 'field_main_slider_image',
// 					'label' => 'Main Image',
// 					'name' => 'main_image',
// 					'type' => 'image',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'return_format' => 'url',
// 					'preview_size' => 'medium',
// 					'library' => 'all',
// 				),
// 				array(
// 					'key' => 'field_icon_image',
// 					'label' => 'Icon Image',
// 					'name' => 'icon_image',
// 					'type' => 'image',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'return_format' => 'url',
// 					'preview_size' => 'medium',
// 					'library' => 'all',
// 				),
// 				array(
// 					'key' => 'field_gallery',
// 					'label' => 'Gallery',
// 					'name' => 'gallery',
// 					'type' => 'gallery',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'min' => '',
// 					'max' => '',
// 					'preview_size' => 'medium',
// 					'insert' => 'append',
// 					'library' => 'all',
// 				),
// 			),
// 		),

// 		// Group 2: Img Field
// 		array(
// 			'key' => 'field_5df69e3e23ecd',
// 			'label' => 'Image',
// 			'name' => 'image',
// 			'type' => 'image',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'return_format' => 'array',
// 			'preview_size' => 'medium',
// 			'library' => 'all',
// 			'min_width' => '',
// 			'min_height' => '',
// 			'min_size' => '',
// 			'max_width' => '',
// 			'max_height' => '',
// 			'max_size' => '',
// 			'mime_types' => '',
// 		),
// 	),
// 	'location' => array(
// 		array(
// 			array(
// 				'param' => 'block',
// 				'operator' => '==',
// 				'value' => 'acf/slider',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => true,
// 	'description' => '',
// ));

// endif;
?>
